---
- name: execute show command in router
  hosts: myrouter
  connection: local    

  tasks:
    - name: execute show command in router
      iosxe_exec_command:
        username: "{{ username }}"
        password: "{{ password }}"
        command: "{{ command }}"
        host: "{{ inventory_hostname }}"
